[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = ["M","s"]
run  = "plugin sshfs -- menu"
desc = "Open SSHFS options"

[[mgr.prepend_keymap]]
on   = ["C","y"]
run  = 'shell -- wl-copy file://$@ -t text/uri-list'
desc = "Copy file to clipboard"

[[mgr.prepend_keymap]]
on = ["C", "p"]
run = 'shell ~/.local/bin/yazi/wlpaste --block'
desc = "Paste from clipboard"
